"""Fill in a module description here"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_cli.ipynb.

# %% auto 0
__all__ = ['app', 'init', 'migrations', 'migrate']

# %% ../nbs/01_cli.ipynb 3
import typer
from rich import print
import subprocess

# %% ../nbs/01_cli.ipynb 4
app = typer.Typer(name="FH Template Helper")

# %% ../nbs/01_cli.ipynb 5
@app.command()
def init():
    """
    Initialize the development environment using uv or venv.
    """
    print("[yellow]Checking if uv is installed...[/yellow]")
    try:
        # Check if uv is installed
        subprocess.run(["uv", "--version"], check=True, capture_output=True)
        print("[green]uv is installed. Creating new environment...[/green]")
        
        # Create and activate environment using uv
        subprocess.run(["uv", "sync"], check=True)
        print("[green]Dependencies installed successfully![/green]")
        
    except subprocess.CalledProcessError:
        # If uv is not installed, offer choice
        print("[yellow]uv is not installed. Would you like to:[/yellow]")
        print("1) Install uv (recommended)")
        print("2) Continue with standard venv")
        
        choice = typer.prompt("Enter choice", type=int, default=1)
        
        if choice == 1:
            print("[yellow]Installing uv...[/yellow]")
            # Install uv using curl
            subprocess.run(
                ["curl", "-LsSf", "https://astral.sh/uv/install.sh"],
                stdout=subprocess.PIPE,
                check=True
            )
            subprocess.run(["uv", "venv", ".venv"], check=True)
            subprocess.run([".venv/bin/uv", "pip", "install", "-e", "."], check=True)
        else:
            print("[yellow]Creating standard venv environment...[/yellow]")
            subprocess.run(["python", "-m", "venv", ".venv"], check=True)
            subprocess.run([".venv/bin/pip", "install", "-e", "."], check=True)
        
        print("[green]Environment created and dependencies installed![/green]")


# %% ../nbs/01_cli.ipynb 6
@app.command()
def migrations(message: str = typer.Option("Pushing changes", help="Optional migration message")):
    """
    Automate Alembic migration generation.
    """
    print(f"Generating Alembic migration with message: {message}")
    try:
        # alembic revision --autogenerate -m "Pushing changes"
        subprocess.run(["alembic", "revision", "--autogenerate", "-m", message], check=True)
        print("[green]Migration created successfully![/green]")
    except subprocess.CalledProcessError as e:
        print(f"[red]Error running Alembic: {e}[/red]")


# %% ../nbs/01_cli.ipynb 7
@app.command()
def migrate():
    """
    Apply all pending Alembic migrations.
    """
    print("[yellow]Applying database migrations...[/yellow]")
    try:
        subprocess.run(["alembic", "upgrade", "head"], check=True)
        print("[green]Migrations applied successfully![/green]")
    except subprocess.CalledProcessError as e:
        print(f"[red]Error applying migrations: {e}[/red]")


# %% ../nbs/01_cli.ipynb 8
if __name__ == "__main__":
    app()
