"""Pushing changes

Revision ID: 465b8aeaebdb
Revises: e9f632dc4afc
Create Date: 2024-12-18 20:25:03.510504

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy import Text


# revision identifiers, used by Alembic.
revision: str = '465b8aeaebdb'
down_revision: Union[str, None] = 'e9f632dc4afc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
