"""Pushing changes

Revision ID: ec79a7493e5c
Revises: 465b8aeaebdb
Create Date: 2024-12-18 23:00:16.346788

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy import Text


# revision identifiers, used by Alembic.
revision: str = 'ec79a7493e5c'
down_revision: Union[str, None] = '465b8aeaebdb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
